server:
  port: 8080

spring:
  application:
    name: api-gateway
    
  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  # Include app name in MDC (so the %X{springApplicationName} resolves)
  # Boot already correlates logs via MDC (traceId/spanId) when Micrometer Tracing is present.
  pattern:
    # If you prefer property-based correlation instead of custom logback:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0               # demo: sample 100% so every request gets a trace
    # W3C is the default propagation; add B3 too if you still talk to older Boot 2/Sleuth services:
    propagation:
      produce: [W3C, B3]             # optional; default is W3C only
      consume: [W3C, B3, B3_MULTI]   # default includes these
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus  # prometheus is optional text view only
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}