server:
  port: 8081

spring:
  application:
    name: hello-service
  config:
    import: "optional:configserver:"  # no URL → discover via Eureka
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: "${spring.application.name}:${server.port}"

management.endpoints.web.exposure.include: health,info